### ISSUE TITLE
Bugs

### ISSUE THREAD

**Issue by RevenBot** [RevenBot/WordleSolver#18]
```[tasklist]
### Tasks
- [ ] Word not found
- [ ] Fix Pepega Aiuola List
- [ ] New method to insert words
```
